
package cn.hpn.bos.crm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import cn.hpn.bos.crm.Customer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.crm.hpn.cn/")
@XmlSeeAlso({
})
public interface ICustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<cn.hpn.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findNotAssociation", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindNotAssociation")
    @ResponseWrapper(localName = "findNotAssociationResponse", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindNotAssociationResponse")
    public List<Customer> findNotAssociation();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.hpn.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHasAssociation", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindHasAssociation")
    @ResponseWrapper(localName = "findHasAssociationResponse", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindHasAssociationResponse")
    public List<Customer> findHasAssociation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.hpn.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.hpn.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedzoneIdByaddress", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindDecidedzoneIdByaddress")
    @ResponseWrapper(localName = "findDecidedzoneIdByaddressResponse", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.FindDecidedzoneIdByaddressResponse")
    public String findDecidedzoneIdByaddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "decidedzoneAssociationCustomer", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.DecidedzoneAssociationCustomer")
    @ResponseWrapper(localName = "decidedzoneAssociationCustomerResponse", targetNamespace = "http://service.crm.hpn.cn/", className = "cn.hpn.crm.service.DecidedzoneAssociationCustomerResponse")
    public void decidedzoneAssociationCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

}
